# Generated by Django 3.2 on 2021-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movil', '0002_alter_door_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='ip',
            field=models.CharField(default=-1.0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
